"""initial schema

Revision ID: 0001
Revises: 
Create Date: 2026-10-07 06:34:54.873054

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '0001'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # Hand-added: sequence behind trip numbers (T-000001, T-000002, ...).
    op.execute("CREATE SEQUENCE trip_no_seq")

    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('admin_users',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('username', sa.String(length=60), nullable=False),
    sa.Column('role', sa.Enum('admin', 'viewer', name='admin_role'), nullable=False),
    sa.Column('password_hash', sa.String(length=255), nullable=False),
    sa.Column('status', sa.Enum('active', 'inactive', name='admin_user_status'), server_default='active', nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_admin_users')),
    sa.UniqueConstraint('username', name=op.f('uq_admin_users_username'))
    )
    op.create_table('drivers',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('employee_id', sa.String(length=40), nullable=False),
    sa.Column('name', sa.String(length=120), nullable=False),
    sa.Column('phone', sa.String(length=30), nullable=True),
    sa.Column('license_no', sa.String(length=60), nullable=True),
    sa.Column('pin_hash', sa.String(length=255), nullable=True),
    sa.Column('status', sa.Enum('active', 'inactive', name='driver_status'), server_default='active', nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_drivers')),
    sa.UniqueConstraint('employee_id', name=op.f('uq_drivers_employee_id'))
    )
    op.create_table('passengers',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('employee_id', sa.String(length=40), nullable=False),
    sa.Column('name', sa.String(length=120), nullable=False),
    sa.Column('department', sa.String(length=120), nullable=True),
    sa.Column('phone', sa.String(length=30), nullable=True),
    sa.Column('status', sa.Enum('active', 'inactive', name='passenger_status'), server_default='active', nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_passengers')),
    sa.UniqueConstraint('employee_id', name=op.f('uq_passengers_employee_id'))
    )
    op.create_table('vehicles',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('car_code', sa.String(length=20), nullable=False),
    sa.Column('reg_number', sa.String(length=40), nullable=False),
    sa.Column('model', sa.String(length=80), nullable=False),
    sa.Column('current_km', sa.Integer(), server_default='0', nullable=False),
    sa.Column('status', sa.Enum('active', 'maintenance', 'inactive', name='vehicle_status'), server_default='active', nullable=False),
    sa.Column('qr_version', sa.Integer(), server_default='1', nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint('current_km >= 0', name=op.f('ck_vehicles_current_km_nonneg')),
    sa.CheckConstraint('qr_version >= 1', name=op.f('ck_vehicles_qr_version_positive')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_vehicles')),
    sa.UniqueConstraint('car_code', name=op.f('uq_vehicles_car_code')),
    sa.UniqueConstraint('reg_number', name=op.f('uq_vehicles_reg_number'))
    )
    op.create_table('settings',
    sa.Column('key', sa.String(length=80), nullable=False),
    sa.Column('value', sa.String(length=255), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_by', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['updated_by'], ['admin_users.id'], name=op.f('fk_settings_updated_by_admin_users')),
    sa.PrimaryKeyConstraint('key', name=op.f('pk_settings'))
    )
    op.create_table('trips',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('trip_no', sa.String(length=20), server_default=sa.text("'T-' || lpad(nextval('trip_no_seq')::text, 6, '0')"), nullable=False),
    sa.Column('vehicle_id', sa.Integer(), nullable=False),
    sa.Column('driver_id', sa.Integer(), nullable=False),
    sa.Column('passenger_id', sa.Integer(), nullable=True),
    sa.Column('with_passenger', sa.Boolean(), nullable=False),
    sa.Column('purpose', sa.Text(), nullable=True),
    sa.Column('start_km', sa.Integer(), nullable=False),
    sa.Column('end_km', sa.Integer(), nullable=True),
    sa.Column('start_place', sa.String(length=255), nullable=False),
    sa.Column('start_lat', sa.Numeric(precision=9, scale=6), nullable=True),
    sa.Column('start_lng', sa.Numeric(precision=9, scale=6), nullable=True),
    sa.Column('end_place', sa.String(length=255), nullable=True),
    sa.Column('end_lat', sa.Numeric(precision=9, scale=6), nullable=True),
    sa.Column('end_lng', sa.Numeric(precision=9, scale=6), nullable=True),
    sa.Column('destination', sa.String(length=255), nullable=False),
    sa.Column('start_time', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('journey_start_time', sa.DateTime(timezone=True), nullable=True),
    sa.Column('end_time', sa.DateTime(timezone=True), nullable=True),
    sa.Column('end_confirm_time', sa.DateTime(timezone=True), nullable=True),
    sa.Column('distance_km', sa.Integer(), nullable=True),
    sa.Column('status', sa.Enum('waiting_for_passenger', 'in_progress', 'waiting_for_end_confirm', 'completed', 'cancelled', 'closed_by_admin', name='trip_status'), nullable=False),
    sa.Column('close_reason', sa.Text(), nullable=True),
    sa.Column('needs_review', sa.Boolean(), server_default=sa.text('false'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint("status NOT IN ('cancelled','closed_by_admin') OR (close_reason IS NOT NULL AND length(btrim(close_reason)) > 0)", name=op.f('ck_trips_reason_required_when_stopped')),
    sa.CheckConstraint("status NOT IN ('waiting_for_end_confirm','completed') OR (end_km IS NOT NULL AND end_time IS NOT NULL)", name=op.f('ck_trips_ended_trip_has_end_data')),
    sa.CheckConstraint('distance_km IS NULL OR distance_km >= 0', name=op.f('ck_trips_distance_nonneg')),
    sa.CheckConstraint('end_km IS NULL OR end_km > start_km', name=op.f('ck_trips_end_after_start')),
    sa.CheckConstraint('start_km >= 0', name=op.f('ck_trips_start_km_nonneg')),
    sa.CheckConstraint('with_passenger OR (purpose IS NOT NULL AND length(btrim(purpose)) > 0)', name=op.f('ck_trips_purpose_required_without_passenger')),
    sa.ForeignKeyConstraint(['driver_id'], ['drivers.id'], name=op.f('fk_trips_driver_id_drivers')),
    sa.ForeignKeyConstraint(['passenger_id'], ['passengers.id'], name=op.f('fk_trips_passenger_id_passengers')),
    sa.ForeignKeyConstraint(['vehicle_id'], ['vehicles.id'], name=op.f('fk_trips_vehicle_id_vehicles')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_trips')),
    sa.UniqueConstraint('trip_no', name=op.f('uq_trips_trip_no'))
    )
    op.create_index('ix_trips_driver_id', 'trips', ['driver_id'], unique=False)
    op.create_index('ix_trips_passenger_id', 'trips', ['passenger_id'], unique=False)
    op.create_index('ix_trips_start_time', 'trips', ['start_time'], unique=False)
    op.create_index('ix_trips_status', 'trips', ['status'], unique=False)
    op.create_index('ix_trips_vehicle_id', 'trips', ['vehicle_id'], unique=False)
    op.create_index('uq_trips_one_open_per_driver', 'trips', ['driver_id'], unique=True, postgresql_where=sa.text("status IN ('waiting_for_passenger','in_progress','waiting_for_end_confirm')"))
    op.create_index('uq_trips_one_open_per_vehicle', 'trips', ['vehicle_id'], unique=True, postgresql_where=sa.text("status IN ('waiting_for_passenger','in_progress','waiting_for_end_confirm')"))
    op.create_table('alerts',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('trip_id', sa.Integer(), nullable=True),
    sa.Column('vehicle_id', sa.Integer(), nullable=True),
    sa.Column('type', sa.Enum('km_gap', 'long_trip', 'waiting_too_long', 'wrong_ids', 'high_km', 'admin_closed', name='alert_type'), nullable=False),
    sa.Column('message', sa.Text(), nullable=False),
    sa.Column('status', sa.Enum('open', 'solved', name='alert_status'), server_default='open', nullable=False),
    sa.Column('note', sa.Text(), nullable=True),
    sa.Column('resolved_by', sa.Integer(), nullable=True),
    sa.Column('resolved_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint("status <> 'solved' OR (resolved_by IS NOT NULL AND resolved_at IS NOT NULL)", name=op.f('ck_alerts_solved_has_resolver')),
    sa.ForeignKeyConstraint(['resolved_by'], ['admin_users.id'], name=op.f('fk_alerts_resolved_by_admin_users')),
    sa.ForeignKeyConstraint(['trip_id'], ['trips.id'], name=op.f('fk_alerts_trip_id_trips')),
    sa.ForeignKeyConstraint(['vehicle_id'], ['vehicles.id'], name=op.f('fk_alerts_vehicle_id_vehicles')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_alerts'))
    )
    op.create_index('ix_alerts_status', 'alerts', ['status'], unique=False)
    op.create_index('ix_alerts_trip_id', 'alerts', ['trip_id'], unique=False)
    op.create_index('ix_alerts_vehicle_id', 'alerts', ['vehicle_id'], unique=False)
    op.create_table('trip_events',
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.Column('trip_id', sa.Integer(), nullable=True),
    sa.Column('event', sa.String(length=80), nullable=False),
    sa.Column('actor', sa.String(length=120), nullable=True),
    sa.Column('device', sa.String(length=255), nullable=True),
    sa.Column('ip', sa.String(length=45), nullable=True),
    sa.Column('lat', sa.Numeric(precision=9, scale=6), nullable=True),
    sa.Column('lng', sa.Numeric(precision=9, scale=6), nullable=True),
    sa.Column('detail', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['trip_id'], ['trips.id'], name=op.f('fk_trip_events_trip_id_trips')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_trip_events'))
    )
    op.create_index('ix_trip_events_created_at', 'trip_events', ['created_at'], unique=False)
    op.create_index('ix_trip_events_trip_id', 'trip_events', ['trip_id'], unique=False)

    # Hand-added: the audit log is append-only (PDF: "never edited").
    op.execute(
        """
        CREATE FUNCTION trip_events_block_change() RETURNS trigger AS $$
        BEGIN
            RAISE EXCEPTION 'trip_events is append-only (% blocked)', TG_OP;
        END;
        $$ LANGUAGE plpgsql
        """
    )
    op.execute(
        """
        CREATE TRIGGER trip_events_append_only
        BEFORE UPDATE OR DELETE ON trip_events
        FOR EACH ROW EXECUTE FUNCTION trip_events_block_change()
        """
    )
    op.create_table('trip_photos',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('trip_id', sa.Integer(), nullable=False),
    sa.Column('kind', sa.Enum('start', 'end', name='trip_photo_kind'), nullable=False),
    sa.Column('file_url', sa.String(length=500), nullable=False),
    sa.Column('taken_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['trip_id'], ['trips.id'], name=op.f('fk_trip_photos_trip_id_trips')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_trip_photos')),
    sa.UniqueConstraint('trip_id', 'kind', name='uq_trip_photos_trip_kind')
    )
    op.create_table('trip_tokens',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('trip_id', sa.Integer(), nullable=False),
    sa.Column('kind', sa.Enum('start', 'end', name='trip_token_kind'), nullable=False),
    sa.Column('token_hash', sa.String(length=64), nullable=False),
    sa.Column('expires_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('used_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('revoked_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('failed_attempts', sa.Integer(), server_default='0', nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint('failed_attempts >= 0', name=op.f('ck_trip_tokens_failed_attempts_nonneg')),
    sa.ForeignKeyConstraint(['trip_id'], ['trips.id'], name=op.f('fk_trip_tokens_trip_id_trips')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_trip_tokens')),
    sa.UniqueConstraint('token_hash', name=op.f('uq_trip_tokens_token_hash'))
    )
    op.create_index('ix_trip_tokens_trip_id', 'trip_tokens', ['trip_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_trip_tokens_trip_id', table_name='trip_tokens')
    op.drop_table('trip_tokens')
    op.drop_table('trip_photos')
    op.execute("DROP TRIGGER trip_events_append_only ON trip_events")
    op.execute("DROP FUNCTION trip_events_block_change()")
    op.drop_index('ix_trip_events_trip_id', table_name='trip_events')
    op.drop_index('ix_trip_events_created_at', table_name='trip_events')
    op.drop_table('trip_events')
    op.drop_index('ix_alerts_vehicle_id', table_name='alerts')
    op.drop_index('ix_alerts_trip_id', table_name='alerts')
    op.drop_index('ix_alerts_status', table_name='alerts')
    op.drop_table('alerts')
    op.drop_index('uq_trips_one_open_per_vehicle', table_name='trips', postgresql_where=sa.text("status IN ('waiting_for_passenger','in_progress','waiting_for_end_confirm')"))
    op.drop_index('uq_trips_one_open_per_driver', table_name='trips', postgresql_where=sa.text("status IN ('waiting_for_passenger','in_progress','waiting_for_end_confirm')"))
    op.drop_index('ix_trips_vehicle_id', table_name='trips')
    op.drop_index('ix_trips_status', table_name='trips')
    op.drop_index('ix_trips_start_time', table_name='trips')
    op.drop_index('ix_trips_passenger_id', table_name='trips')
    op.drop_index('ix_trips_driver_id', table_name='trips')
    op.drop_table('trips')
    op.drop_table('settings')
    op.drop_table('vehicles')
    op.drop_table('passengers')
    op.drop_table('drivers')
    op.drop_table('admin_users')
    # ### end Alembic commands ###

    # Hand-added: autogenerate does not drop the sequence or the enum types.
    op.execute("DROP SEQUENCE trip_no_seq")
    for enum_name in (
        "admin_role", "admin_user_status", "driver_status", "passenger_status",
        "vehicle_status", "trip_status", "trip_photo_kind", "trip_token_kind",
        "alert_type", "alert_status",
    ):
        op.execute(f"DROP TYPE {enum_name}")
