"""visitor passengers

Revision ID: 0002
Revises: 0001
Create Date: 2026-10-08 11:05:45.497523

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '0002'
down_revision: Union[str, Sequence[str], None] = '0001'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('trips', sa.Column('is_visitor', sa.Boolean(), server_default=sa.text('false'), nullable=False))
    op.add_column('trips', sa.Column('visitor_name', sa.String(length=120), nullable=True))
    op.add_column('trips', sa.Column('visitor_phone', sa.String(length=30), nullable=True))
    op.add_column('trips', sa.Column('visitor_reason', sa.String(length=255), nullable=True))
    # ### end Alembic commands ###

    # Hand-added: autogenerate does not detect CHECK constraints.
    op.create_check_constraint(
        op.f('ck_trips_visitor_has_details'), 'trips',
        "NOT is_visitor OR (visitor_name IS NOT NULL AND visitor_phone IS NOT NULL AND passenger_id IS NULL)",
    )
    op.create_check_constraint(
        op.f('ck_trips_visitor_fields_only_for_visitors'), 'trips',
        "is_visitor OR (visitor_name IS NULL AND visitor_phone IS NULL AND visitor_reason IS NULL)",
    )


def downgrade() -> None:
    """Downgrade schema."""
    op.drop_constraint(op.f('ck_trips_visitor_fields_only_for_visitors'), 'trips', type_='check')
    op.drop_constraint(op.f('ck_trips_visitor_has_details'), 'trips', type_='check')
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('trips', 'visitor_reason')
    op.drop_column('trips', 'visitor_phone')
    op.drop_column('trips', 'visitor_name')
    op.drop_column('trips', 'is_visitor')
    # ### end Alembic commands ###
